site_name: Shortcuts for Chrome
site_description: Chrome navigation menu for technical users.
docs_dir: docs
site_url: https://oss.mobilefirst.me/shortcuts-for-chrome/
repo_url: https://github.com/MobileFirstLLC/shortcuts-for-chrome
repo_name: shortcuts-for-chrome
edit_uri: blob/main/docs/pages
use_directory_urls: true

nav:
  - About: index.md
  - Install:
    - Chrome Web Store: https://chrome.google.com/webstore/detail/shortcuts-for-chrome/jnmekaomnicdcpgdndekkmojfomifjal
  - Development:
    - Introduction: description.md
    - Getting Started Guide: dev.md
    - Source Code Docs: api.md
    - License: https://github.com/MobileFirstLLC/shortcuts-for-chrome/blob/main/LICENSE
  - Translate: translate.md
  - Release Notes: changelog.md
  - Privacy Policy: privacy.md

extra_css:
  - style.css

theme:
  name: material
  logo: /shortcuts-for-chrome/favicon.png
  favicon: /shortcuts-for-chrome/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
  palette:
    scheme: light
    primary: indigo
    accent: blue
  font:
    text: Inter
    code: Fira Mono

plugins:
  - mermaid2:

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - meta
  - attr_list
  - md_in_html
  - def_list
  - footnotes